name: Download Artifact
description: Download all build files

runs:
  using: "composite"
  steps:
   # - name: Checkout Repository
     # uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
